version: "3.7"
services:
  mysql-server:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - spring-boot-mysql-network-backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bankmgmt
      - MYSQL_USERNAME=raouene
      - MYSQL_PASSWORD=raouene
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 3
  spring-boot-mysql:
    image: raouenembarek/bank-management-backend:0.1
    ports:
      - "9090:9090"
    networks:
      - spring-boot-mysql-network-backend
      - spring-boot-mysql-network-frontend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-server:3306/bankmgmt?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      mysql-server:
        condition: service_healthy
  angular-app:
    image: raouenembarek/bank-management-frontend:dev
    ports:
      - "4200:80"
    networks:
      - spring-boot-mysql-network-frontend
    environment:
      - apiUrl=http://spring-boot-mysql
    depends_on:
      - spring-boot-mysql
networks:
  spring-boot-mysql-network-backend:
  spring-boot-mysql-network-frontend: