apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
  annotations:
    app: backend
data:
  application.properties: |-
    server.port=9090
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=create
    spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true
    spring.datasource.username=root
    spring.datasource.password=${MYSQL_ROOT_PASSWORD}
    spring.datasource.initialization-mode=always
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL57InnoDBDialect
