apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-data
  labels:
    app: database
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
