apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-data
  labels:
    app: database
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: database
