apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bank-management
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-bank-management
        image: raouenembarek/bank-management-frontend:0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 4200
          name: http
